// SPEC6 §14.2: `apt-cacher-ultra --print-apt-conf` prints a
// recommended apt-conf snippet to stdout for the operator to drop
// into `/etc/apt/apt.conf.d/00aptcacher`. Output shape:
//
//   # Generated by apt-cacher-ultra --print-apt-conf
//   Acquire::http::Proxy "http://<advertised-host>:<port>";
//   Acquire::https::Proxy "http://<advertised-host>:<port>";
//
// When `tls_mitm.enabled = true` AND a CA cert is materialized on
// disk, four trailing comment lines name the CA fingerprint and
// path so the operator's distribution playbook has a single source
// of truth.
//
// **Advertised host resolution** (§14.2 priority):
//   1. `cache.advertise_host` if non-empty (port appended from
//      `cache.listen` if absent).
//   2. Otherwise `cache.listen` if its host is unicast.
//   3. Otherwise (`0.0.0.0` / `::` / empty host): exit 5.
//
// Exit codes:
//   - 0: snippet printed
//   - 1: config file unreadable
//   - 5: cache.listen binds unspecified address with no advertise_host

package main

import (
	"crypto/sha256"
	"crypto/x509"
	"encoding/hex"
	"encoding/pem"
	"fmt"
	"io"
	"net"
	"os"
	"path/filepath"
	"strings"

	"github.com/linsomniac/apt-cacher-ultra/internal/config"
)

// runPrintAptConf is the §14.2 entry point. configPath is the same
// `-config` value the daemon would consume; stdout receives the
// snippet, stderr receives diagnostics. Returns the §14.2 exit code.
func runPrintAptConf(configPath string, stdout, stderr io.Writer) int {
	cfg, err := config.Load(configPath)
	if err != nil {
		fmt.Fprintf(stderr, "print-apt-conf: load config %q: %v\n", configPath, err)
		return 1
	}
	advertised, err := resolveAdvertisedHostPort(cfg)
	if err != nil {
		fmt.Fprintf(stderr, "print-apt-conf: %v\n", err)
		return 5
	}

	proxyURL := "http://" + advertised
	fmt.Fprintln(stdout, "# Generated by apt-cacher-ultra --print-apt-conf")
	fmt.Fprintf(stdout, "Acquire::http::Proxy %q;\n", proxyURL)
	fmt.Fprintf(stdout, "Acquire::https::Proxy %q;\n", proxyURL)

	if cfg.TlsMitm.Enabled {
		path, fp := peekCAFingerprint(cfg)
		if fp != "" {
			fmt.Fprintln(stdout, "# When MITM is enabled, the following CA must be installed")
			fmt.Fprintln(stdout, "# system-wide (e.g. via update-ca-certificates) for HTTPS")
			fmt.Fprintln(stdout, "# repositories in sources.list to validate:")
			fmt.Fprintf(stdout, "# CA fingerprint (SHA-256): %s\n", fp)
			fmt.Fprintf(stdout, "# CA path on the cache host: %s\n", path)
		} else {
			fmt.Fprintf(stderr, "print-apt-conf: tls_mitm.enabled = true but no CA found at %q; run `apt-cacher-ultra ca print > ca.crt` first to materialize the CA, then re-run --print-apt-conf for a complete snippet\n", path)
		}
	}
	return 0
}

// resolveAdvertisedHostPort applies the §14.2 priority. The host
// emitted in the snippet must be unambiguously routable — the daemon
// binds 0.0.0.0/:: by default, but a snippet that emits those is
// useless to a fleet client.
func resolveAdvertisedHostPort(cfg *config.Config) (string, error) {
	if ah := cfg.Cache.AdvertiseHost; ah != "" {
		// Already includes a port? Use verbatim.
		if _, _, err := net.SplitHostPort(ah); err == nil {
			return ah, nil
		}
		// No port → append the listen port. JoinHostPort handles
		// IPv4/DNS automatically; if the operator wrote a bracketed
		// IPv6 like "[::1]" with no port, JoinHostPort would re-bracket
		// the inner literal, producing a doubly-bracketed mess. Strip
		// pre-existing brackets first so the result is a single layer.
		_, listenPort, err := net.SplitHostPort(cfg.Cache.Listen)
		if err != nil {
			return "", fmt.Errorf("parse cache.listen %q: %w", cfg.Cache.Listen, err)
		}
		if strings.HasPrefix(ah, "[") && strings.HasSuffix(ah, "]") {
			return ah + ":" + listenPort, nil
		}
		return net.JoinHostPort(ah, listenPort), nil
	}

	listenHost, listenPort, err := net.SplitHostPort(cfg.Cache.Listen)
	if err != nil {
		return "", fmt.Errorf("parse cache.listen %q: %w", cfg.Cache.Listen, err)
	}
	if listenHost == "" || listenHost == "0.0.0.0" || listenHost == "::" {
		return "", fmt.Errorf("cache.listen=%q binds an unspecified address; set cache.advertise_host to a client-facing hostname or pin cache.listen to a unicast address", cfg.Cache.Listen)
	}
	return net.JoinHostPort(listenHost, listenPort), nil
}

// peekCAFingerprint reads the on-disk CA cert (operator-supplied
// path or auto-gen `<storage_dir>/ca.crt`) and returns (path, sha256
// hex). Returns ("path", "") on any failure — file missing, parse
// fail, etc. The caller emits a stderr note. This function NEVER
// generates a CA: the side-effect-free peek is the right primitive
// for a `--print-apt-conf` invocation that may run before any
// daemon (or `ca print`) has materialized one.
func peekCAFingerprint(cfg *config.Config) (string, string) {
	var path string
	if cfg.TlsMitm.CaCert != "" {
		path = cfg.TlsMitm.CaCert
	} else {
		path = filepath.Join(cfg.EffectiveCaStorageDir(), "ca.crt")
	}
	pemBytes, err := os.ReadFile(path)
	if err != nil {
		return path, ""
	}
	blk, _ := pem.Decode(pemBytes)
	if blk == nil || blk.Type != "CERTIFICATE" {
		return path, ""
	}
	cert, err := x509.ParseCertificate(blk.Bytes)
	if err != nil {
		return path, ""
	}
	sum := sha256.Sum256(cert.Raw)
	return path, hex.EncodeToString(sum[:])
}
