package tlsmitm

import (
	"crypto"
	"crypto/ecdsa"
	"crypto/ed25519"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/rsa"
	"crypto/sha256"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/hex"
	"encoding/pem"
	"errors"
	"fmt"
	"io/fs"
	"math/big"
	"os"
	"path/filepath"
	"strings"
	"syscall"
	"time"
)

// Source identifies whether a CA was loaded from operator-supplied
// paths or auto-generated by the daemon. SPEC6 §10.2 mitm_ca_loaded
// `source` field.
type Source int

const (
	SourceGenerated Source = iota
	SourceSupplied
)

func (s Source) String() string {
	switch s {
	case SourceGenerated:
		return "generated"
	case SourceSupplied:
		return "supplied"
	default:
		return "unknown"
	}
}

// CA is the loaded (or freshly generated) trust anchor the MITM
// CONNECT handler signs leaf certs with. The struct is immutable after
// construction; callers should treat it as read-only.
type CA struct {
	Cert       *x509.Certificate
	PrivateKey crypto.PrivateKey

	// TLSCert is `Cert` packaged in *tls.Certificate form for direct
	// use as the CA argument to GenerateLeaf. The Leaf field is
	// populated; Certificate[0] is the CA's own DER.
	TLSCert *tls.Certificate

	// Source records where the trust anchor came from for the
	// §10.2 mitm_ca_loaded log line.
	Source Source

	// FingerprintSHA256 is the lower-cased hex form of sha256(Cert.Raw).
	// Operators see this in the loud-config startup log AND in the
	// `ca.ready` marker file. SPEC6 §4.2.
	FingerprintSHA256 string

	// NameConstraints lists the dNSName permittedSubtrees the CA
	// carries. Empty when the CA was generated unconstrained (the
	// operator opted in via tls_mitm.allow_unconstrained_ca = true)
	// OR when an operator-supplied CA carries no constraint extension.
	NameConstraints []string

	// NameConstraintsSkippedReason is non-empty ONLY when the CA was
	// auto-generated WITHOUT constraints because the regex was empty
	// or untranslatable AND the operator opted in. The reason is the
	// human-readable diagnostic emitted in the
	// mitm_ca_name_constraints_skipped Warn. Empty in every other case.
	NameConstraintsSkippedReason string
}

// LoadOptions parameterizes LoadOrGenerate. A typical caller (the
// daemon main + `ca print` subcommand) populates this from the
// validated [tls_mitm] config block.
type LoadOptions struct {
	// SuppliedCertPath / SuppliedKeyPath select the operator-supplied
	// path when both are non-empty. When empty, the auto-generated
	// path runs against StorageDir.
	SuppliedCertPath string
	SuppliedKeyPath  string

	// StorageDir is the directory the auto-gen path materializes
	// `ca.crt`, `ca.key`, `ca.ready`, and `.ca.lock` into. Required
	// when both SuppliedCertPath and SuppliedKeyPath are empty.
	StorageDir string

	// AllowedHostRegex is the §5.1.2 signing predicate used to derive
	// Name Constraints on the auto-generated CA. Has no effect on the
	// operator-supplied path.
	AllowedHostRegex string

	// AllowUnconstrainedCA, when true, lets the auto-gen path proceed
	// when AllowedHostRegex is empty or untranslatable — emitting a
	// `mitm_ca_name_constraints_skipped` Warn instead of refusing.
	// SPEC6 §5.1.1 fail-closed default is false.
	AllowUnconstrainedCA bool

	// CALifetime is how far in the future the auto-generated CA's
	// `not_after` is set. Defaults to 10 years per §5.1.1 if zero.
	CALifetime time.Duration

	// Subject overrides the auto-generated CA subject. Defaults to
	// CN=apt-cacher-ultra CA, O=apt-cacher-ultra. SPEC6 §5.1.1.
	Subject pkix.Name

	// Now is the wall-clock source for not_before/not_after and the
	// not_after-in-the-future check on supplied CAs. Defaults to
	// time.Now.
	Now func() time.Time

	// LockTimeout is how long the §4.2.2 flock acquire blocks before
	// failing with `mitm_ca_lock_timeout`. Defaults to 30s.
	LockTimeout time.Duration

	// LogFn is the structured-event sink. Implementations forward to
	// slog (level: "info" / "warn" / "error"). nil = swallow events,
	// useful in tests. The package emits the §10.2 events relevant to
	// the CA path (mitm_ca_generated, mitm_ca_loaded,
	// mitm_ca_name_constraints_skipped, mitm_ca_unconstrained_refused,
	// mitm_ca_lock_timeout, mitm_ca_load_failed,
	// mitm_ca_generation_failed).
	LogFn func(level, event string, fields map[string]any)
}

// LoadOrGenerate is the single entry point: it dispatches to the
// operator-supplied path or the auto-generated path based on the
// presence of SuppliedCertPath/SuppliedKeyPath. SPEC6 §4.2.
func LoadOrGenerate(opts LoadOptions) (*CA, error) {
	opts = opts.withDefaults()
	if opts.SuppliedCertPath != "" || opts.SuppliedKeyPath != "" {
		return loadSupplied(opts)
	}
	if opts.StorageDir == "" {
		return nil, errors.New("tlsmitm: LoadOrGenerate: empty StorageDir and no operator-supplied CA")
	}
	return loadOrGenerateAuto(opts)
}

func (o LoadOptions) withDefaults() LoadOptions {
	if o.Now == nil {
		o.Now = time.Now
	}
	if o.CALifetime == 0 {
		o.CALifetime = 10 * 365 * 24 * time.Hour
	}
	if o.LockTimeout == 0 {
		o.LockTimeout = 30 * time.Second
	}
	if o.Subject.CommonName == "" {
		o.Subject = pkix.Name{
			CommonName:   "apt-cacher-ultra CA",
			Organization: []string{"apt-cacher-ultra"},
		}
	}
	if o.LogFn == nil {
		o.LogFn = func(level, event string, fields map[string]any) {}
	}
	return o
}

// ============================================================================
// Operator-supplied path
// ============================================================================

func loadSupplied(opts LoadOptions) (*CA, error) {
	if opts.SuppliedCertPath == "" || opts.SuppliedKeyPath == "" {
		return nil, errors.New("tlsmitm: tls_mitm.ca_cert and tls_mitm.ca_key must both be set or both empty")
	}
	certPEM, err := os.ReadFile(opts.SuppliedCertPath)
	if err != nil {
		return nil, fmt.Errorf("tlsmitm: reading ca_cert %q: %w", opts.SuppliedCertPath, err)
	}
	keyPEM, err := os.ReadFile(opts.SuppliedKeyPath)
	if err != nil {
		return nil, fmt.Errorf("tlsmitm: reading ca_key %q: %w", opts.SuppliedKeyPath, err)
	}
	cert, err := parseCertPEM(certPEM)
	if err != nil {
		return nil, fmt.Errorf("tlsmitm: ca_cert %q: %w", opts.SuppliedCertPath, err)
	}
	key, err := parseKeyPEM(keyPEM)
	if err != nil {
		return nil, fmt.Errorf("tlsmitm: ca_key %q: %w", opts.SuppliedKeyPath, err)
	}
	if err := validateSuppliedCA(cert, key, opts.Now()); err != nil {
		return nil, err
	}
	ca := &CA{
		Cert:              cert,
		PrivateKey:        key,
		TLSCert:           &tls.Certificate{Certificate: [][]byte{cert.Raw}, PrivateKey: key, Leaf: cert},
		Source:            SourceSupplied,
		FingerprintSHA256: fingerprintHex(cert.Raw),
		NameConstraints:   extractDNSNameConstraints(cert),
	}
	opts.LogFn("info", "mitm_ca_loaded", map[string]any{
		"source":             ca.Source.String(),
		"fingerprint_sha256": ca.FingerprintSHA256,
		"not_after_unixtime": cert.NotAfter.Unix(),
		"name_constraints":   len(ca.NameConstraints) > 0,
	})
	return ca, nil
}

// validateSuppliedCA enforces SPEC6 §5.2 / §11 F4-F6/F6a checks on an
// operator-supplied CA pair.
//
// The KeyUsage check guards against a CA cert that *parses* fine but
// would have every leaf signing rejected by Go's x509.CreateCertificate
// (which enforces the keyCertSign bit when KeyUsage is present). An
// absent KeyUsage extension (cert.KeyUsage == 0) is treated as
// "all usages permitted", matching Go's stdlib behavior — failing
// closed there would reject every operator-supplied CA without a
// KeyUsage extension, which is overly strict.
func validateSuppliedCA(cert *x509.Certificate, key crypto.PrivateKey, now time.Time) error {
	if !cert.IsCA || !cert.BasicConstraintsValid {
		return errors.New("tlsmitm: supplied CA cert lacks BasicConstraints CA:TRUE")
	}
	if cert.KeyUsage != 0 && cert.KeyUsage&x509.KeyUsageCertSign == 0 {
		return errors.New("tlsmitm: supplied CA cert has KeyUsage extension without keyCertSign — leaf signing would fail at every CONNECT")
	}
	if !now.Before(cert.NotAfter) {
		return fmt.Errorf("tlsmitm: supplied CA cert not_after %s is not in the future (now=%s)", cert.NotAfter, now)
	}
	if err := keysMatch(cert.PublicKey, key); err != nil {
		return fmt.Errorf("tlsmitm: supplied CA cert/key mismatch: %w", err)
	}
	if _, err := SigningAlgFor(key); err != nil {
		return err
	}
	return nil
}

// keysMatch verifies cert.PublicKey == key.Public(). Done with a typed
// switch so the comparison is correctness-equivalent across ECDSA / RSA
// key types — a raw == on crypto.PublicKey would compare interface
// fat-pointer values and miss matching keys with different memory
// layouts.
func keysMatch(certPub crypto.PublicKey, key crypto.PrivateKey) error {
	signer, ok := key.(crypto.Signer)
	if !ok {
		return fmt.Errorf("private key %T does not implement crypto.Signer", key)
	}
	keyPub := signer.Public()
	switch ck := certPub.(type) {
	case *ecdsa.PublicKey:
		kk, ok := keyPub.(*ecdsa.PublicKey)
		if !ok {
			return fmt.Errorf("cert public key is ECDSA, private key is %T", keyPub)
		}
		if ck.Curve != kk.Curve || ck.X.Cmp(kk.X) != 0 || ck.Y.Cmp(kk.Y) != 0 {
			return errors.New("ECDSA public key parameters disagree")
		}
		return nil
	case *rsa.PublicKey:
		kk, ok := keyPub.(*rsa.PublicKey)
		if !ok {
			return fmt.Errorf("cert public key is RSA, private key is %T", keyPub)
		}
		if ck.N.Cmp(kk.N) != 0 || ck.E != kk.E {
			return errors.New("RSA public key parameters disagree")
		}
		return nil
	case ed25519.PublicKey:
		kk, ok := keyPub.(ed25519.PublicKey)
		if !ok {
			return fmt.Errorf("cert public key is Ed25519, private key is %T", keyPub)
		}
		if !ck.Equal(kk) {
			return errors.New("Ed25519 public key bytes disagree")
		}
		// SigningAlgFor will reject Ed25519 separately; we still report
		// match-OK here so the rejection comes through with the key-type
		// reason rather than a spurious mismatch reason.
		return nil
	default:
		return fmt.Errorf("unsupported cert public key type %T", certPub)
	}
}

func parseCertPEM(b []byte) (*x509.Certificate, error) {
	block, _ := pem.Decode(b)
	if block == nil {
		return nil, errors.New("no PEM block found")
	}
	if block.Type != "CERTIFICATE" {
		return nil, fmt.Errorf("expected PEM type CERTIFICATE, got %q", block.Type)
	}
	cert, err := x509.ParseCertificate(block.Bytes)
	if err != nil {
		return nil, fmt.Errorf("parse: %w", err)
	}
	return cert, nil
}

func parseKeyPEM(b []byte) (crypto.PrivateKey, error) {
	block, _ := pem.Decode(b)
	if block == nil {
		return nil, errors.New("no PEM block found")
	}
	switch block.Type {
	case "PRIVATE KEY":
		return x509.ParsePKCS8PrivateKey(block.Bytes)
	case "RSA PRIVATE KEY":
		return x509.ParsePKCS1PrivateKey(block.Bytes)
	case "EC PRIVATE KEY":
		return x509.ParseECPrivateKey(block.Bytes)
	default:
		return nil, fmt.Errorf("unsupported PEM type %q", block.Type)
	}
}

// ============================================================================
// Auto-generated path
// ============================================================================

const (
	caCertFile  = "ca.crt"
	caKeyFile   = "ca.key"
	caReadyFile = "ca.ready"
	caLockFile  = ".ca.lock"
)

func loadOrGenerateAuto(opts LoadOptions) (*CA, error) {
	// §4.2.1 step 1: acquire interprocess flock.
	if err := ensurePrivateDir(opts.StorageDir); err != nil {
		return nil, err
	}
	lockPath := filepath.Join(opts.StorageDir, caLockFile)
	release, err := acquireLock(lockPath, opts.LockTimeout)
	if err != nil {
		opts.LogFn("error", "mitm_ca_lock_timeout", map[string]any{"path": lockPath})
		opts.LogFn("error", "mitm_ca_generation_failed", map[string]any{"path": opts.StorageDir, "err": err.Error()})
		return nil, err
	}
	defer release()

	// §4.2 case detection — under lock so the state is stable.
	state, err := scanCAState(opts.StorageDir)
	if err != nil {
		opts.LogFn("error", "mitm_ca_load_failed", map[string]any{"path": opts.StorageDir, "err": err.Error()})
		return nil, err
	}
	switch state.kind {
	case caStateClean:
		// Case 1: no real files committed — generate. Cleanup tmp residue
		// is part of the generate path (step 3).
		return generateAndPersist(opts)
	case caStateCommitted:
		// Case 2: load.
		ca, err := loadCommittedCA(opts.StorageDir, state, opts.Now())
		if err != nil {
			opts.LogFn("error", "mitm_ca_load_failed", map[string]any{"path": opts.StorageDir, "err": err.Error()})
			return nil, err
		}
		// Best-effort *.tmp cleanup under the lock.
		_ = cleanupTmpFiles(opts.StorageDir)
		opts.LogFn("info", "mitm_ca_loaded", map[string]any{
			"source":             ca.Source.String(),
			"fingerprint_sha256": ca.FingerprintSHA256,
			"not_after_unixtime": ca.Cert.NotAfter.Unix(),
			"name_constraints":   len(ca.NameConstraints) > 0,
		})
		return ca, nil
	case caStateInconsistent:
		opts.LogFn("error", "mitm_ca_load_failed", map[string]any{
			"path": opts.StorageDir,
			"err":  state.reason,
		})
		return nil, fmt.Errorf("tlsmitm: %s — operator must remove daemon-managed real files (ca.crt, ca.key, ca.ready) within %q to force regeneration on next start", state.reason, opts.StorageDir)
	default:
		return nil, fmt.Errorf("tlsmitm: internal: unhandled CA state kind %d", state.kind)
	}
}

// caStateKind enumerates the §4.2 state-detection rule.
type caStateKind int

const (
	caStateClean        caStateKind = iota // no real files committed (case 1)
	caStateCommitted                       // ca.crt + ca.key + ca.ready present, fingerprints checked at load time (case 2)
	caStateInconsistent                    // any non-clean partial state (case 3)
)

type caState struct {
	kind   caStateKind
	reason string // human-readable diagnostic for caStateInconsistent
}

// scanCAState examines the daemon-managed real files in `dir` and
// returns the §4.2 case classification. *.tmp files are intentionally
// IGNORED — they are generation residue, never trust anchors. The
// case-3 trigger is "real file present without committed siblings".
func scanCAState(dir string) (caState, error) {
	hasCert, certInfo, err := statFile(dir, caCertFile)
	if err != nil {
		return caState{}, err
	}
	hasKey, keyInfo, err := statFile(dir, caKeyFile)
	if err != nil {
		return caState{}, err
	}
	hasReady, _, err := statFile(dir, caReadyFile)
	if err != nil {
		return caState{}, err
	}
	_ = certInfo
	_ = keyInfo

	// Case 1: nothing committed.
	if !hasCert && !hasKey && !hasReady {
		return caState{kind: caStateClean}, nil
	}
	// Case 2 vs case 3 must both have all three real files.
	if !hasCert || !hasKey || !hasReady {
		return caState{
			kind: caStateInconsistent,
			reason: fmt.Sprintf(
				"inconsistent CA state in %q: ca.crt=%v ca.key=%v ca.ready=%v (a real file is present without its committed siblings)",
				dir, hasCert, hasKey, hasReady,
			),
		}, nil
	}
	return caState{kind: caStateCommitted}, nil
}

func statFile(dir, name string) (bool, fs.FileInfo, error) {
	info, err := os.Stat(filepath.Join(dir, name))
	if err == nil {
		return true, info, nil
	}
	if errors.Is(err, fs.ErrNotExist) {
		return false, nil, nil
	}
	return false, nil, fmt.Errorf("stat %s/%s: %w", dir, name, err)
}

// loadCommittedCA reads the ca.crt + ca.key + ca.ready trio under the
// committed-state branch and validates self-consistency. Any failure
// here surfaces as case-3 mitm_ca_load_failed at the caller.
func loadCommittedCA(dir string, _ caState, now time.Time) (*CA, error) {
	certPath := filepath.Join(dir, caCertFile)
	keyPath := filepath.Join(dir, caKeyFile)
	readyPath := filepath.Join(dir, caReadyFile)

	certPEM, err := os.ReadFile(certPath)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", certPath, err)
	}
	keyPEM, err := os.ReadFile(keyPath)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", keyPath, err)
	}
	readyBytes, err := os.ReadFile(readyPath)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", readyPath, err)
	}

	cert, err := parseCertPEM(certPEM)
	if err != nil {
		return nil, fmt.Errorf("ca.crt parse: %w", err)
	}
	key, err := parseKeyPEM(keyPEM)
	if err != nil {
		return nil, fmt.Errorf("ca.key parse: %w", err)
	}
	if err := keysMatch(cert.PublicKey, key); err != nil {
		return nil, fmt.Errorf("ca.crt/ca.key mismatch: %w", err)
	}
	// Marker fingerprint check — hash the parsed DER (the canonical
	// "cert fingerprint" form, matching `openssl x509 -fingerprint`).
	// Hashing the file bytes would be PEM-encoding-dependent; the DER
	// is the cert itself.
	wantFp := strings.TrimSpace(string(readyBytes))
	gotFp := fingerprintHex(cert.Raw)
	if !strings.EqualFold(wantFp, gotFp) {
		return nil, fmt.Errorf("ca.ready fingerprint %q does not match sha256(ca.crt DER) %q", wantFp, gotFp)
	}
	if !now.Before(cert.NotAfter) {
		return nil, fmt.Errorf("ca.crt not_after %s is not in the future (now=%s)", cert.NotAfter, now)
	}
	if !cert.IsCA || !cert.BasicConstraintsValid {
		return nil, errors.New("ca.crt lacks BasicConstraints CA:TRUE")
	}
	if _, err := SigningAlgFor(key); err != nil {
		return nil, err
	}
	return &CA{
		Cert:              cert,
		PrivateKey:        key,
		TLSCert:           &tls.Certificate{Certificate: [][]byte{cert.Raw}, PrivateKey: key, Leaf: cert},
		Source:            SourceGenerated,
		FingerprintSHA256: gotFp,
		NameConstraints:   extractDNSNameConstraints(cert),
	}, nil
}

// generateAndPersist runs the §4.2.1 atomic write path under the lock.
// All errors here surface as `mitm_ca_generation_failed` Error.
func generateAndPersist(opts LoadOptions) (*CA, error) {
	// §4.2.1 step 3: cleanup any *.tmp residue from a prior crashed run
	// before we begin writing fresh tmp files.
	if err := cleanupTmpFiles(opts.StorageDir); err != nil {
		opts.LogFn("error", "mitm_ca_generation_failed", map[string]any{"path": opts.StorageDir, "err": err.Error()})
		return nil, err
	}

	// Decide constraint posture BEFORE generating: a translation failure
	// with allow_unconstrained_ca=false short-circuits the whole path.
	permitted, transErr := TranslateRegex(opts.AllowedHostRegex)
	skippedReason := ""
	if transErr != nil {
		if !opts.AllowUnconstrainedCA {
			opts.LogFn("error", "mitm_ca_unconstrained_refused", map[string]any{
				"regex":  opts.AllowedHostRegex,
				"reason": transErr.Error(),
			})
			opts.LogFn("error", "mitm_ca_generation_failed", map[string]any{
				"path": opts.StorageDir,
				"err":  transErr.Error(),
			})
			return nil, fmt.Errorf("tlsmitm: refusing to generate unconstrained CA: %w (set tls_mitm.allow_unconstrained_ca=true to opt in, or narrow tls_mitm.allowed_host_regex)", transErr)
		}
		skippedReason = transErr.Error()
		permitted = nil
	}

	// Generate ECDSA P-256 CA key.
	caKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		opts.LogFn("error", "mitm_ca_generation_failed", map[string]any{"path": opts.StorageDir, "err": err.Error()})
		return nil, fmt.Errorf("tlsmitm: generate CA key: %w", err)
	}

	now := opts.Now()
	serialMax := new(big.Int).Lsh(big.NewInt(1), 128)
	serial, err := rand.Int(rand.Reader, serialMax)
	if err != nil {
		return nil, fmt.Errorf("tlsmitm: serial: %w", err)
	}
	if serial.Sign() == 0 {
		serial = big.NewInt(1)
	}
	tmpl := &x509.Certificate{
		SerialNumber:          serial,
		Subject:               opts.Subject,
		NotBefore:             now.Add(-5 * time.Minute),
		NotAfter:              now.Add(opts.CALifetime),
		KeyUsage:              x509.KeyUsageDigitalSignature | x509.KeyUsageCertSign | x509.KeyUsageCRLSign,
		ExtKeyUsage:           []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		BasicConstraintsValid: true,
		IsCA:                  true,
		MaxPathLen:            0,
		MaxPathLenZero:        true,
		SignatureAlgorithm:    x509.ECDSAWithSHA256,
	}
	if len(permitted) > 0 {
		tmpl.PermittedDNSDomainsCritical = true
		tmpl.PermittedDNSDomains = append([]string(nil), permitted...)
	}

	der, err := x509.CreateCertificate(rand.Reader, tmpl, tmpl, &caKey.PublicKey, caKey)
	if err != nil {
		opts.LogFn("error", "mitm_ca_generation_failed", map[string]any{"path": opts.StorageDir, "err": err.Error()})
		return nil, fmt.Errorf("tlsmitm: sign CA cert: %w", err)
	}
	cert, err := x509.ParseCertificate(der)
	if err != nil {
		return nil, fmt.Errorf("tlsmitm: parse generated cert: %w", err)
	}

	// PEM-encode for on-disk persistence.
	certPEMBuf := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der})
	keyDER, err := x509.MarshalPKCS8PrivateKey(caKey)
	if err != nil {
		return nil, fmt.Errorf("tlsmitm: marshal CA key: %w", err)
	}
	keyPEMBuf := pem.EncodeToMemory(&pem.Block{Type: "PRIVATE KEY", Bytes: keyDER})

	derFp := fingerprintHex(der)
	if err := writeCAAtomically(opts.StorageDir, certPEMBuf, keyPEMBuf, derFp); err != nil {
		opts.LogFn("error", "mitm_ca_generation_failed", map[string]any{"path": opts.StorageDir, "err": err.Error()})
		return nil, err
	}

	ca := &CA{
		Cert:                         cert,
		PrivateKey:                   caKey,
		TLSCert:                      &tls.Certificate{Certificate: [][]byte{der}, PrivateKey: caKey, Leaf: cert},
		Source:                       SourceGenerated,
		FingerprintSHA256:            derFp,
		NameConstraints:              append([]string(nil), permitted...),
		NameConstraintsSkippedReason: skippedReason,
	}

	// §10.2 Info — CA generated.
	opts.LogFn("info", "mitm_ca_generated", map[string]any{
		"path":             opts.StorageDir,
		"algorithm":        "ecdsa-p256",
		"lifetime_seconds": int64(opts.CALifetime.Seconds()),
	})
	if skippedReason != "" {
		opts.LogFn("warn", "mitm_ca_name_constraints_skipped", map[string]any{
			"regex":  opts.AllowedHostRegex,
			"reason": skippedReason,
		})
	}
	opts.LogFn("info", "mitm_ca_loaded", map[string]any{
		"source":             ca.Source.String(),
		"fingerprint_sha256": ca.FingerprintSHA256,
		"not_after_unixtime": ca.Cert.NotAfter.Unix(),
		"name_constraints":   len(ca.NameConstraints) > 0,
	})
	return ca, nil
}

// writeCAStep names a SPEC6 §4.2.1 numbered step that writeCAAtomically
// performs. The values exist solely so tests can inject a synthetic
// failure at a chosen step (via writeCAStepHook) and assert the
// resulting on-disk state matches the §4.2.1 disposition table.
type writeCAStep int

const (
	stepWriteCertTmp  writeCAStep = iota // §4.2.1 step 5
	stepWriteKeyTmp                      // step 6
	stepRenameCert                       // step 7a
	stepRenameKey                        // step 7b
	stepFsyncDir1                        // step 8
	stepWriteReadyTmp                    // step 9
	stepRenameReady                      // step 10a
	stepFsyncDir2                        // step 10b (final)
)

func (s writeCAStep) String() string {
	switch s {
	case stepWriteCertTmp:
		return "write-ca.crt.tmp"
	case stepWriteKeyTmp:
		return "write-ca.key.tmp"
	case stepRenameCert:
		return "rename-ca.crt"
	case stepRenameKey:
		return "rename-ca.key"
	case stepFsyncDir1:
		return "fsync-dir-1"
	case stepWriteReadyTmp:
		return "write-ca.ready.tmp"
	case stepRenameReady:
		return "rename-ca.ready"
	case stepFsyncDir2:
		return "fsync-dir-2"
	}
	return "unknown"
}

// writeCAStepHook is a TEST-ONLY fault-injection seam. Production code
// leaves it nil. When non-nil, writeCAAtomically calls it BEFORE each
// numbered §4.2.1 step; a non-nil error short-circuits that step (and
// every subsequent step) so the cleanup-and-return path runs exactly
// as it would for a real I/O failure.
//
// Tests use setWriteCAStepHookForTest, which returns a restore closure
// for use in defer. Reads/writes of this var are not synchronized — the
// fault-injection tests are sequential.
var writeCAStepHook func(writeCAStep) error

// setWriteCAStepHookForTest installs a step hook and returns a restore
// closure callers should defer. Use to drive fault-injection tests.
func setWriteCAStepHookForTest(h func(writeCAStep) error) func() {
	prev := writeCAStepHook
	writeCAStepHook = h
	return func() { writeCAStepHook = prev }
}

// writeCAAtomically materializes the cert + key + marker trio per
// SPEC6 §4.2.1 steps 4–11. Caller holds the §4.2.2 flock.
//
// `markerFP` is the lower-cased hex sha256 of the cert's DER bytes
// (the standard "cert fingerprint" form `openssl x509 -fingerprint`
// emits). The marker file content is exactly that string plus a
// trailing newline.
//
// On any failure, the partial *.tmp residue is best-effort cleaned up
// so the next start doesn't trip case 3 on this run's residue. Real
// committed files are not touched on failure (and won't exist anyway —
// renames happen only after successful Sync).
func writeCAAtomically(dir string, certPEM, keyPEM []byte, markerFP string) (retErr error) {
	defer func() {
		if retErr != nil {
			_ = cleanupTmpFiles(dir)
		}
	}()

	// loadOrGenerateAuto already ran ensurePrivateDir before acquiring
	// the flock; this is belt-and-suspenders for any future caller that
	// reaches this function on a different code path.
	if err := ensurePrivateDir(dir); err != nil {
		return err
	}

	fail := func(s writeCAStep) error {
		if writeCAStepHook == nil {
			return nil
		}
		return writeCAStepHook(s)
	}

	if err := fail(stepWriteCertTmp); err != nil {
		return fmt.Errorf("tlsmitm: write ca.crt.tmp: %w", err)
	}
	if err := writeFileSync(filepath.Join(dir, caCertFile+".tmp"), certPEM, 0o600); err != nil {
		return fmt.Errorf("tlsmitm: write ca.crt.tmp: %w", err)
	}
	if err := fail(stepWriteKeyTmp); err != nil {
		return fmt.Errorf("tlsmitm: write ca.key.tmp: %w", err)
	}
	if err := writeFileSync(filepath.Join(dir, caKeyFile+".tmp"), keyPEM, 0o600); err != nil {
		return fmt.Errorf("tlsmitm: write ca.key.tmp: %w", err)
	}
	if err := fail(stepRenameCert); err != nil {
		return fmt.Errorf("tlsmitm: rename ca.crt: %w", err)
	}
	if err := os.Rename(filepath.Join(dir, caCertFile+".tmp"), filepath.Join(dir, caCertFile)); err != nil {
		return fmt.Errorf("tlsmitm: rename ca.crt: %w", err)
	}
	if err := fail(stepRenameKey); err != nil {
		return fmt.Errorf("tlsmitm: rename ca.key: %w", err)
	}
	if err := os.Rename(filepath.Join(dir, caKeyFile+".tmp"), filepath.Join(dir, caKeyFile)); err != nil {
		return fmt.Errorf("tlsmitm: rename ca.key: %w", err)
	}
	if err := fail(stepFsyncDir1); err != nil {
		return fmt.Errorf("tlsmitm: fsync dir after rename: %w", err)
	}
	if err := fsyncDir(dir); err != nil {
		return fmt.Errorf("tlsmitm: fsync dir after rename: %w", err)
	}
	if err := fail(stepWriteReadyTmp); err != nil {
		return fmt.Errorf("tlsmitm: write ca.ready.tmp: %w", err)
	}
	marker := markerFP + "\n"
	if err := writeFileSync(filepath.Join(dir, caReadyFile+".tmp"), []byte(marker), 0o600); err != nil {
		return fmt.Errorf("tlsmitm: write ca.ready.tmp: %w", err)
	}
	if err := fail(stepRenameReady); err != nil {
		return fmt.Errorf("tlsmitm: rename ca.ready: %w", err)
	}
	if err := os.Rename(filepath.Join(dir, caReadyFile+".tmp"), filepath.Join(dir, caReadyFile)); err != nil {
		return fmt.Errorf("tlsmitm: rename ca.ready: %w", err)
	}
	if err := fail(stepFsyncDir2); err != nil {
		return fmt.Errorf("tlsmitm: fsync dir after marker: %w", err)
	}
	if err := fsyncDir(dir); err != nil {
		return fmt.Errorf("tlsmitm: fsync dir after marker: %w", err)
	}
	return nil
}

// writeFileSync writes data to path with the given mode and fsyncs the
// file before close. The file is created with O_EXCL — if a stale
// *.tmp lingers (despite cleanup), the rename layer will refuse and
// the operator sees a clear error.
func writeFileSync(path string, data []byte, mode os.FileMode) error {
	f, err := os.OpenFile(path, os.O_CREATE|os.O_WRONLY|os.O_EXCL, mode)
	if err != nil {
		// Tolerate residual tmp files from a previous crashed run that
		// weren't cleaned for any reason — overwrite cleanly. This is
		// safe because we hold the flock and we're the only writer.
		if errors.Is(err, fs.ErrExist) {
			if rerr := os.Remove(path); rerr != nil {
				return fmt.Errorf("remove stale %s: %w", path, rerr)
			}
			f, err = os.OpenFile(path, os.O_CREATE|os.O_WRONLY|os.O_EXCL, mode)
		}
		if err != nil {
			return err
		}
	}
	if _, err := f.Write(data); err != nil {
		_ = f.Close()
		return err
	}
	if err := f.Sync(); err != nil {
		_ = f.Close()
		return err
	}
	return f.Close()
}

func fsyncDir(dir string) error {
	d, err := os.Open(dir)
	if err != nil {
		return err
	}
	defer d.Close()
	return d.Sync()
}

// ensurePrivateDir guarantees that `dir` exists, is a real directory,
// and has mode 0700. SPEC6 §4.2.1 step 4 says "Create <ca_storage_dir>
// with mode 0700 if absent. umask is irrelevant — the daemon explicitly
// chmods." A bare os.MkdirAll honors umask AND only sets the mode on
// directories it creates — a pre-existing 0755 dir keeps its mode.
// This helper closes that gap: chmod after stat, re-stat to confirm
// the chmod landed (some filesystems silently drop mode changes), and
// fail loudly if any of those steps cannot complete. The CA's private
// key sits inside this directory and the path-traversal mode matters.
func ensurePrivateDir(dir string) error {
	if dir == "" {
		return errors.New("tlsmitm: ensurePrivateDir: empty path")
	}
	info, err := os.Stat(dir)
	if err != nil {
		if !errors.Is(err, fs.ErrNotExist) {
			return fmt.Errorf("tlsmitm: stat %s: %w", dir, err)
		}
		if err := os.MkdirAll(dir, 0o700); err != nil {
			return fmt.Errorf("tlsmitm: create %s: %w", dir, err)
		}
		info, err = os.Stat(dir)
		if err != nil {
			return fmt.Errorf("tlsmitm: stat %s after create: %w", dir, err)
		}
	}
	if !info.IsDir() {
		return fmt.Errorf("tlsmitm: %s exists but is not a directory", dir)
	}
	if info.Mode().Perm() == 0o700 {
		return nil
	}
	if err := os.Chmod(dir, 0o700); err != nil {
		return fmt.Errorf("tlsmitm: chmod %s 0700: %w", dir, err)
	}
	info2, err := os.Stat(dir)
	if err != nil {
		return fmt.Errorf("tlsmitm: re-stat %s: %w", dir, err)
	}
	if info2.Mode().Perm() != 0o700 {
		return fmt.Errorf("tlsmitm: %s mode is %v after chmod 0700 (filesystem may not support permissions)", dir, info2.Mode().Perm())
	}
	return nil
}

func cleanupTmpFiles(dir string) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return nil
		}
		return err
	}
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		if strings.HasSuffix(e.Name(), ".tmp") {
			_ = os.Remove(filepath.Join(dir, e.Name()))
		}
	}
	return nil
}

func fingerprintHex(b []byte) string {
	sum := sha256.Sum256(b)
	return hex.EncodeToString(sum[:])
}

// extractDNSNameConstraints returns the dNSName permittedSubtrees the
// supplied cert carries (or nil if none). Phase 6 only ever inspects
// dNSName; iPAddress / email / URI subtrees are not Phase 6 surface.
func extractDNSNameConstraints(cert *x509.Certificate) []string {
	if len(cert.PermittedDNSDomains) == 0 {
		return nil
	}
	out := make([]string, len(cert.PermittedDNSDomains))
	copy(out, cert.PermittedDNSDomains)
	return out
}

// ============================================================================
// Interprocess flock
// ============================================================================

// acquireLock takes an exclusive flock on `path`, polling at 100ms
// granularity until acquired or `timeout` elapses. The returned
// release function unlocks and closes the file descriptor.
//
// SPEC6 §4.2.2: flock is FD-tied, not pathname-tied. We MUST hold the
// FD open until release, so the file is not closed in this function's
// happy path — only in `release`.
func acquireLock(path string, timeout time.Duration) (release func(), err error) {
	f, err := os.OpenFile(path, os.O_CREATE|os.O_RDWR, 0o600)
	if err != nil {
		return nil, fmt.Errorf("tlsmitm: open flock %q: %w", path, err)
	}
	deadline := time.Now().Add(timeout)
	for {
		err := syscall.Flock(int(f.Fd()), syscall.LOCK_EX|syscall.LOCK_NB)
		if err == nil {
			return func() {
				_ = syscall.Flock(int(f.Fd()), syscall.LOCK_UN)
				_ = f.Close()
			}, nil
		}
		if !errors.Is(err, syscall.EWOULDBLOCK) {
			_ = f.Close()
			return nil, fmt.Errorf("tlsmitm: flock %q: %w", path, err)
		}
		if !time.Now().Before(deadline) {
			_ = f.Close()
			return nil, fmt.Errorf("tlsmitm: flock %q: timeout after %s", path, timeout)
		}
		time.Sleep(100 * time.Millisecond)
	}
}
